function git_domain()
{
  if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
      local email=$(git config user.email)
      local domain=${${email#*@}%%.*}
      local branch=$(git symbolic-ref --short HEAD)

      echo " ($domain) ($branch)"
  fi
}

function dotfiles_sync()
{
  cd ~/.config/nvim
  mv init.lua "init.lua.$(date +%s).backup"
  wget "https://raw.githubusercontent.com/stefan-moraru/dotfiles/refs/heads/main/config/nvim/init.lua" -O "init.lua"

  cd ~
  mv .zshrc ".zshrc.$(date +%s).backup"
  wget "https://raw.githubusercontent.com/stefan-moraru/dotfiles/refs/heads/main/config/zsh/zshrc" -O ".zshrc"

  cd ~/.config/ghostty
  mv config "config.$(date +%s).backup"
  wget "https://raw.githubusercontent.com/stefan-moraru/dotfiles/refs/heads/main/config/ghostty/config" -O "config"
}

setopt prompt_subst

PROMPT='%B%F{cyan}%~%f%b%F{green}$(git_domain)%f $ '

# zsh setup
export HISTSIZE=50000
export SAVEHIST=$HISTSIZE
setopt share_history

# Variables
export CLICOLOR=1

export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH="./node_modules/.bin/:$PATH"

export PNPM_HOME="/Users/stefanmoraru/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"

export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

export PATH="$PATH:$HOME/.rvm/bin"

export N_PREFIX="/opt/homebrew"

# Aliases
alias vim="nvim"
alias vi="nvim"

alias ga="git add"
alias gd="git diff"
alias gs="git status"
alias gsf="git status -uno"
alias gpr="git pull --rebase"

# Plugins
eval "$(zoxide init zsh)"

source ~/.zsh_exports
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
